### PR TITLE
🚀 Added new constants, restarting Guild.ts. 

### PR DESCRIPTION
**Pull request by PraveshKunwar**
Added new constants in src/constants, need to restart guild.ts with constructor (tmrw or later).  If someone wants to create an interface for this: https://discord.com/developers/docs/resources/guild 

Im going to use it in the constructor for Guild.ts, don't have to do it. lmk if there are any issues

### CODE REVIEW

**Comment by PraveshKunwar** [comment]
🚀 Added Guild.ts, constructor will be fixed tmrw.

**Comment by eternalmoon1234** [comment]
Wow, thank you so much for the PR.

**Comment by eternalmoon1234** [comment]
Do you want me to merge it tmrw?

**Comment by PraveshKunwar** [comment]
You can merge it whenever you like, if you want to wait for others to review that's fine, but it should be ok to merge.

**Comment by eternalmoon1234** [comment]
Sounds good.

**Comment by eternalmoon1234** [comment]
Looks awesome, thanks for the PR.

**Review by eternalmoon1234 — APPROVED** [review]

**Comment by PraveshKunwar** [comment]
🚀 Added new constants for Guild.ts, and I am almost finished with the constructor.

**Review by nerdthatnoonelikes — APPROVED** [review]

**Pull request merged**
