### PR TITLE
feat(TextChannel): add some methods + interfaces

### PR DESCRIPTION
**Pull request by eternalmoon1234**
I added some invite-related methods and interfaces for the TextChannel structure, but I still need to assign API data, just thought I'd write some methods. 

Also, I am thinking that instead of a **getInvite()** method, we can create syntax like **invites.get()** which will look cleaner. To do this, I can create an InvitesManager class with methods such as **get()**, **delete()**, **create()**, and add the InvitesManager class as a property on TextChannel, which will allow us to achieve that syntax. Does that sound good?

### CODE REVIEW

**Comment by PraveshKunwar** [comment]
Alright sounds good.

**Comment by eternalmoon1234** [comment]
I'll commit that now

**Comment by eternalmoon1234** [comment]
Don't merge yet, I'm still working on two new structs that are not TextChannel, I just figured i'd add them here because why not.

**Comment by PraveshKunwar** [comment]
Sounds good

**Review by PraveshKunwar — APPROVED** [review]
It looks good, I think we need to figure out (for all the structs and managers) how to name them. I think we need to figure out how we should name the methods and stuff so we can be consistent. Looks good tho so far, hopefully Salvage can get some reviews in later as well.

**Comment by eternalmoon1234** [comment]
Alright, I will work on them tonight, I have to go somewhere for a few hours.

**Comment by PraveshKunwar** [comment]
wait why are you making a voicestate structure? I already started that in the previous pr? Please check out that one before you continue on.

**Comment by eternalmoon1234** [comment]
ah, didn't see

**Pull request merged**
