### PR TITLE
Channel structures

### PR DESCRIPTION
**Pull request by gautam-paranjape**
The PR for channel structures, `BaseChannel`, `GuildChannel`, and all the channel types

### CODE REVIEW

**Comment by gautam-paranjape** [comment]
Ready to review, I added the bases of a bunch of new structures related to Channels, especially GuildChannel, so we can work on properties and methods.

**Review by PraveshKunwar — APPROVED** [review]
looks good

**Comment by gautam-paranjape** [comment]
alright

**Comment by gautam-paranjape** [comment]
next, i think we should focus on adding properties to all the structures i made, and then methods, we can both work on it together off of a PR

**Review by nerdthatnoonelikes — APPROVED** [review]
Looks good.

**Comment by gautam-paranjape** [comment]
Alright, I'm going to merge

**Pull request merged**
